/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head'
import styles from '../styles/Layout.module.scss'


import Nav from '../components/Nav'
import Footer from '../components/Footer'
import Contact from '../components/Contact'
import Portfolio from '../components/Portfolio'
import Quote from '../components/Quotes'
import Services from '../components/Services'


export default function Home() {
  return (
    <>
      <div className={styles.home}>
        <Nav />
        <Head>
          <title>Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
            rel="stylesheet" />
        </Head>
        <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: Montserrat;
        }
        * {
          box-sizing: border-box;
        }
      `}
        </style>
        
        <main className={styles.main}>
          <Services />
          <Quote />
          <Portfolio />
          <Contact />
        </main>
        <Footer />
      </div>
    </>
  )
}
