/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head'
import Image from 'next/image'


import styles from '../styles/Layout.module.scss'
// import contactStyles from '../styles/Contact.module.scss'
import Nav from '../components/Nav'
import Footer from '../components/Footer'
import Contact from '../components/Contact'




export default function Home() {


  return (
    <>
      <div className={styles.home}>
        {/* <h1>hello world</h1> */}
        <Nav />
        <Head>
          <title>Next App</title>
          <meta name="description" content="Generated by create next app" />
          {/* <link rel="icon" href="/favicon.ico" /> */}
          <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
            rel="stylesheet" />
        </Head>

        <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: Montserrat;
        }

        * {
          box-sizing: border-box;
        }
      `}
        </style>

        <main className={styles.main}>
          <Contact />
        </main>
        
        <Footer />
      </div>
    </>
  )
}
